"""init

Revision ID: c0a2e7ff7f43
Revises: 
Create Date: 2025-08-07 13:08:15.171293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a2e7ff7f43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.Unicode(length=100), nullable=True),
    sa.Column('full_name', sa.Unicode(length=150), nullable=True),
    sa.Column('title', sa.Unicode(length=150), nullable=True),
    sa.Column('email', sa.Unicode(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='userstatus'), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), nullable=True),
    sa.Column('use_ldap', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
